version: 0.2

env:
  variables:
    pwsh: 'PowerShell-7.0.1-win-x64.msi'

phases:

  install:
    commands:
      - powershell -command '$PSVersionTable'
      - powershell -command '.\configure_aws_credential.ps1'
      - powershell -command '.\install_modules.ps1'

      # Install PowerShell Core
      - aws s3 cp "s3://austoonz-software/$env:pwsh" $env:pwsh --quiet
      - powershell -command "Start-Process -FilePath .\$env:pwsh -ArgumentList '/qn /norestart' -Wait"
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -command ''$PSVersionTable'''
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -command ''.\install_modules.ps1'''

  build:
    commands:
      - powershell -command 'Invoke-Build'
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -command ''Invoke-Build'''

artifacts:
  files:
    - '**/*'
  base-directory: 'DeploymentArtifacts'