version: 0.2

phases:

  pre_build:
    commands:
      - powershell -file '.\configure_aws_credential.ps1'

      # Install for Windows PowerShell
      - powershell -command '$PSVersionTable'
      - powershell -file '.\install_nuget.ps1'
      - powershell -file '.\install_modules.ps1'

      # Install for PowerShell
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -command ''$PSVersionTable'''
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -file ''.\install_nuget.ps1'''
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -file ''.\install_modules.ps1'''

  build:
    commands:
      - powershell -command 'Invoke-Build'
      - '& "C:\Program Files\PowerShell\7\pwsh.exe" -command ''Invoke-Build'''

artifacts:
  files:
    - '**/*'
  base-directory: 'DeploymentArtifacts'