version: 0.2

phases:

  install:
    commands:
      - powershell -command '.\configure_aws_credential.ps1'
      - powershell -command '.\install_modules.ps1'

      # Install PowerShell Core
      - aws s3 cp s3://austoonz-software/PowerShell-6.2.0-win-x64.msi PowerShell-6.2.0-win-x64.msi --quiet
      - powershell -command "Start-Process .\PowerShell-6.2.0-win-x64.msi -ArgumentList '/qn /norestart' -Wait"
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''.\install_modules.ps1'''

  build:
    commands:
      - powershell -command 'Invoke-Build'
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''Invoke-Build'''

artifacts:
  files:
    - '**/*'
  base-directory: 'DeploymentArtifacts'